// Auto-generated from Online Test Catalog Audit CSV. Do not edit manually.
export interface TestRecord {
  testCode: string;
  testName: string;
  medicalApplication: string;
  testingType: string;
}

export const TEST_CATALOG: TestRecord[] = [
  { testCode: "1610", testName: "Proband Whole Genome Sequencing", medicalApplication: "Germline Testing", testingType: "Whole Genome Sequencing" },
  { testCode: "1522", testName: "Custom Sequence Analysis - Prenatal", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "1560", testName: "Custom Proband Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "1580", testName: "Custom Family Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "1593", testName: "Known Familial Variant", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "1594", testName: "Proband Variant Resolution", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "6989", testName: "Positive Control for Custom Sequencing", medicalApplication: "Confirmation Testing", testingType: "Diagnostic Testing" },
  { testCode: "4400", testName: "Neonatal and Infantile Seizures Panel", medicalApplication: "NICU", testingType: "Other" },
  { testCode: "8425", testName: "Rapid FISH Analysis - AneuVysion® (+13/+18/+21 /X/Y)", medicalApplication: "NICU", testingType: "Other" },
  { testCode: "8426", testName: "Rapid FISH Analysis - Sex Chromosome (X/SRY)", medicalApplication: "NICU", testingType: "Other" },
  { testCode: "1533", testName: "Rapid Trio Whole Exome Sequencing + Comprehensive mtDNA Analysis", medicalApplication: "NICU", testingType: "Rapid, Whole Exome Sequencing" },
  { testCode: "1722", testName: "Rapid Trio Whole Exome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Exome Sequencing" },
  { testCode: "1723", testName: "Rapid Duo Whole Exome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Exome Sequencing" },
  { testCode: "1724", testName: "Rapid Quad Whole Exome Sequencing (WES)", medicalApplication: "NICU", testingType: "Rapid, Whole Exome Sequencing" },
  { testCode: "1729", testName: "Rapid Proband Whole Exome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Exome Sequencing" },
  { testCode: "1822", testName: "Rapid Trio Whole Genome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Genome Sequencing" },
  { testCode: "1823", testName: "Rapid Duo Whole Genome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Genome Sequencing" },
  { testCode: "1824", testName: "Rapid Quad Whole Genome Sequencing (WGS)", medicalApplication: "NICU", testingType: "Rapid, Whole Genome Sequencing" },
  { testCode: "1829", testName: "Rapid Proband Whole Genome Sequencing", medicalApplication: "NICU", testingType: "Rapid, Whole Genome Sequencing" },
  { testCode: "25000", testName: "Hematology Profile Panel", medicalApplication: "Oncology", testingType: "Comprehensive Testing" },
  { testCode: "25001", testName: "Hematology Profile Plus Panel", medicalApplication: "Oncology", testingType: "Comprehensive Testing" },
  { testCode: "25002", testName: "Liquid Trace Hematology Panel", medicalApplication: "Oncology", testingType: "Comprehensive Testing" },
  { testCode: "8000", testName: "Oncology FISH Analysis - AML FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8001", testName: "Oncology FISH Analysis - STAT AML FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8005", testName: "Oncology FISH Analysis - MDS FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8006", testName: "Oncology FISH Analysis - STAT MDS FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8007", testName: "Oncology FISH Analysis - Comprehensive MDS/AML FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8008", testName: "Oncology FISH Analysis - STAT Comprehensive MDS/AML FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8010", testName: "Oncology FISH Analysis - ALL FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8012", testName: "Oncology FISH Analysis - ALL Ph-like FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8015", testName: "Oncology FISH Analysis - Multiple Myeloma FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8020", testName: "Oncology FISH Analysis - NHL FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8030", testName: "Oncology FISH Analysis - ALK Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8031", testName: "Oncology FISH Analysis - RET Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8035", testName: "Oncology FISH Analysis - EGFR Amplification", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8040", testName: "Oncology FISH Analysis - CLL FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8055", testName: "Oncology FISH Analysis - 1p/19q Co-deletion", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8080", testName: "Oncology FISH Analysis - TCF3/PBX1 FISH for ALL", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8095", testName: "Oncology FISH Analysis - MET Amplification", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8385", testName: "Oncology FISH Analysis - Gain Chromosome 8", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8705", testName: "Oncology FISH Analysis - MECOM (EVI1)", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8710", testName: "Oncology FISH Analysis - Deletion 5 [MDS]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8715", testName: "Oncology FISH Analysis - Deletion 7 [MDS]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8720", testName: "Oncology FISH Analysis - Deletion 20q12 [MDS]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8725", testName: "Oncology FISH Analysis - AML1/ETO(RUNX1/RUNX1T1): t(8;21) [AML]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8730", testName: "Oncology FISH Analysis - CHIC2: Deleted 4q [Hypereosinophilic Syndrome]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8735", testName: "Oncology FISH Analysis - PML/RARA: t(15;17) [AML]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8740", testName: "Oncology FISH Analysis - CBFB: inv(16) [AML]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8745", testName: "Oncology FISH Analysis - MLL: 11q23", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8750", testName: "Oncology FISH Analysis - BCR/ABL: t(9;22) [CML/ALL/AML]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8755", testName: "Oncology FISH Analysis - TEL/AMLI: t(12;21) [ALL]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8760", testName: "Oncology FISH Analysis - MYC Translocation", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8770", testName: "Oncology FISH Analysis - IGH/CCND1: t(11;14) [Mantle Cell Lymphoma]", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8775", testName: "Oncology FISH Analysis - BCL6 Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8780", testName: "Oncology FISH Analysis - IGH Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8781", testName: "Oncology FISH Analysis - ROS1 Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8785", testName: "Oncology FISH Analysis - BCL2 Rearrangement", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8786", testName: "Oncology FISH Analysis - MALT1 Lymphoma", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8787", testName: "Oncology FISH Analysis - Non-small Cell Lung Carcinoma Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8788", testName: "Oncology FISH Analysis - p53", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8789", testName: "Oncology FISH Analysis - Aggressive/High-Grade B-Cell Lymphoma Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8790", testName: "Oncology FISH Analysis- Multiple Myeloma IgH Rearrangement FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8791", testName: "Oncology FISH Analysis - Eosinophilia FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8792", testName: "Oncology FISH Analysis - ALL Pediatric FISH Panel", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "8795", testName: "Oncology FISH Analysis - IGH/MYC", medicalApplication: "Oncology", testingType: "FISH Testing" },
  { testCode: "BG-24001-P10-1", testName: "Hereditary Melanoma Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P12-1", testName: "Hereditary Prostate Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P12-2", testName: "Hereditary Paraganglioma/Pheochromocytoma Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P18-1", testName: "Hereditary Leukemia/Lymphoma Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P19-1", testName: "Hereditary Renal Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P2-2", testName: "BRCA1 & BRCA2 Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P21-1", testName: "Hereditary Pancreatic Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P22-1", testName: "Hereditary High-Risk Colorectal Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P22-2", testName: "Hereditary Endocrine Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P25-1", testName: "Hereditary Brain/Central Nervous System/Peripheral Nervous System Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P27-1", testName: "Hereditary Breast/Ovarian/Endometrial Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P37-1", testName: "Hereditary Colorectal/Gastrointestinal Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P43-1", testName: "Common Hereditary Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P9-1", testName: "High-Risk Hereditary Breast Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "BG-24001-P94-1", testName: "Comprehensive Hereditary Cancer Panel", medicalApplication: "Oncology", testingType: "Hereditary Cancer" },
  { testCode: "8050", testName: "Oncology Chromosome Analysis - Solid Tumor", medicalApplication: "Oncology", testingType: "Oncology Chromosome Analysis" },
  { testCode: "8300", testName: "Oncology Chromosome Analysis - Hematologic Cancer", medicalApplication: "Oncology", testingType: "Oncology Chromosome Analysis" },
  { testCode: "1300", testName: "BluePrint Panel", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "1560", testName: "Custom Proband Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "1580", testName: "Custom Family Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "1593", testName: "Known Familial Variant", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "1594", testName: "Proband Variant Resolution", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2090", testName: "Low Bone Mass Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2190", testName: "Retinitis Pigmentosa + RPGR orf15 by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2195", testName: "Usher Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2200", testName: "High Bone Mass Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2300", testName: "Myopathy/Rhabdomyolysis Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2554", testName: "ATP7B Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2625", testName: "Collagen, Type I, Alpha 1/2 Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "2663", testName: "FOXRED1 Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3069", testName: "POLG Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3116", testName: "ACADM Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3129", testName: "ALDOB Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3135", testName: "PAH Sequence Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3140", testName: "OTC Sequence Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3166", testName: "PDHA1 Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3309", testName: "ATP8B1 Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3310", testName: "ABCB11 Sequence Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3314", testName: "ABCB11 Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3356", testName: "ACADVL Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3359", testName: "ACADVL Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3429", testName: "ARG1 Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3466", testName: "OPA1 Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3541", testName: "HLCS Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3800", testName: "PYGM Sequence Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "3803", testName: "PYGM Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "4000", testName: "Biochemistry 5-Plex Autism Panel", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "4175", testName: "Biochemistry 3-Plex Autism Panel", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "4400", testName: "Neonatal and Infantile Seizures Panel", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "5274", testName: "PUCD Comprehensive - NGS & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6006", testName: "Angelman Syndrome Methylation Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6031", testName: "Friedreich Ataxia Repeat Expansion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6034", testName: "Huntington Disease Repeat Expansion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6036", testName: "Incontinentia Pigmenti Common Deletion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6037", testName: "Kennedy Disease Repeat Expansion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6041", testName: "Myotonic Dystrophy Type 1 Repeat Expansion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6050", testName: "Prader-Willi Syndrome - Methylation Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6059", testName: "SMN1/SMN2 Copy Number Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6373", testName: "CFTR Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6376", testName: "CFTR Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6573", testName: "FMR1 CGG Repeat Expansion Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "6736", testName: "MECP2 Comprehensive - Sequence & Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "8065", testName: "DXZ1/DYZ3 FISH for Sex Mismatched BMT", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "8405", testName: "FISH Analysis - Custom Familial FISH Studies", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "21900", testName: "MODY Panel by Massively Parallel Sequencing (BCM-NGS?)", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "22100", testName: "Peroxisomal Disorders Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "32870", testName: "MSUD Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "BG-24001-P26-1", testName: "Noonan Spectrum Disorders/RASopathy Panel", medicalApplication: "Pediatrics", testingType: "-" },
  { testCode: "4015", testName: "Comprehensive Creatine and Guanidinoacetate Determination", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4100", testName: "Amino Acid Analysis - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4130", testName: "Creatine and Guanidinoacetate Determination - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4150", testName: "Methylmalonic Acid - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4160", testName: "Amino Acid Analysis - Cerebrospinal Fluid", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4200", testName: "Organic Acid Screen - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4225", testName: "Sulfocysteine Determination - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4240", testName: "Amino Acid Analysis - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4250", testName: "Succinylacetone Determination - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4260", testName: "Creatine and Guanidinoacetate Determination - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4300", testName: "Acylcarnitine Analysis - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4310", testName: "Carnitine Determination - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4330", testName: "Thymidine Determination - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4536", testName: "Arginase Enzyme Analysis", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4555", testName: "Biotinidase Enzyme Analysis", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4569", testName: "Hexosaminidase A & B Enzyme Analysis", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4617", testName: "Tay-Sachs Disease Carrier Testing (Serum)", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4620", testName: "Tay-Sachs Disease Carrier Testing", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4627", testName: "White Blood Cell Cystine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4650", testName: "Phenylbutyrate Metabolite Analysis - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4651", testName: "Phenylbutyrate Metabolite Analysis - Urine", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "4811", testName: "Pyridoxine-Dependent Seizures Panel - Plasma", medicalApplication: "Pediatrics", testingType: "Biochemical Testing" },
  { testCode: "8665", testName: "Chromosomal Microarray Analysis - HR + SNP Screen (Comprehensive)", medicalApplication: "Pediatrics", testingType: "Chromosomal Microarray Analysis" },
  { testCode: "8655", testName: "Chromosomal Microarray Analysis - HR", medicalApplication: "Pediatrics", testingType: "Chromosomal Microarray Analysis" },
  { testCode: "2095", testName: "Fatty Acid Oxidation Deficiency Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "2110", testName: "UCD and Hyperammonemia Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "2125", testName: "GSD Comprehensive Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "2126", testName: "GSD Muscle Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3143", testName: "OTC Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3158", testName: "SLC25A13 Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3238", testName: "SLC25A15 Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3348", testName: "CPS1 Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3353", testName: "NAGS Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "3428", testName: "ARG1 Deletion/Duplication Analysis", medicalApplication: "Pediatrics", testingType: "Metabolic" },
  { testCode: "4900", testName: "Global Metabolomic Assisted Pathway Screen (Global MAPS)®-Plasma", medicalApplication: "Pediatrics", testingType: "Metabolomic Assisted Pathways Screen" },
  { testCode: "4901", testName: "Global Metabolomic Assisted Pathway Screen (Global MAPS)®-Urine", medicalApplication: "Pediatrics", testingType: "Metabolomic Assisted Pathways Screen" },
  { testCode: "1533", testName: "Rapid Trio Whole Exome Sequencing + Comprehensive mtDNA Analysis", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2000", testName: "MitoMet®Plus aCGH Analysis", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2001", testName: "Oligonucleotide aCGH Analysis (Targeted Analysis)", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2003", testName: "Oligonucleotide aCGH Analysis (Targeted Multiple Gene Analysis)", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2010", testName: "Advanced mtDNA Point Mutations and Deletions by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2055", testName: "Comprehensive mtDNA Analysis by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2056", testName: "Targeted mtDNA Analysis by Massively Parallel Sequencing (MitoNGS?)", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2085", testName: "Dual Genome Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2086", testName: "Nuclear Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2130", testName: "MtDNA Depletion/Integrity Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2140", testName: "PEO Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2160", testName: "Mitochondrial Respiratory Chain Complex II Deficiency Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "2180", testName: "Mitochondrial Respiratory Chain Complex I-V Nuclear Gene Deficiency Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3030", testName: "Mitochondrial Nonsyndromic Hearing Loss and Deafness Mutation Panel", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3056", testName: "Mitochondrial Whole Genome Sequence Analysis (Familial Mutation/Variant Analysis)", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3200", testName: "Mitochondrial Respiratory Chain Enzyme Analysis (ETC) - Skeletal Muscle", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3210", testName: "Mitochondrial Respiratory Chain Enzyme Analysis (ETC) - Skin Fibroblasts", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3700", testName: "Mitochondrial DNA Content (qPCR) Analysis - Skeletal Muscle", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "3720", testName: "Mitochondrial DNA Content (qPCR) Analysis - Liver", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "20600", testName: "Dual Genome Leigh Disease Panel by Massively Parallel Sequencing", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing" },
  { testCode: "1532", testName: "Trio Whole Exome Sequencing + Comprehensive mtDNA Analysis", medicalApplication: "Pediatrics", testingType: "Mitochondrial Testing, Whole Exome Sequencing" },
  { testCode: "1520", testName: "Whole Exome Sequencing Reflex", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P142-1", testName: "Neuromuscular Disorders Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P236-1", testName: "Neurodevelopmental Disorders Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P354-1", testName: "Skeletal Disorders Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P397-1", testName: "Epilepsy Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P419-1", testName: "Cerebral Palsy Spectrum Disorders Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P463-1", testName: "Primary Immunodeficiency Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P76-1", testName: "STAT Epilepsy Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "BG-1300-P92-1", testName: "Connective Tissue Disorders Panel", medicalApplication: "Pediatrics", testingType: "NGS Panels" },
  { testCode: "8425", testName: "Rapid FISH Analysis - AneuVysion® (+13/+18/+21 /X/Y)", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8426", testName: "Rapid FISH Analysis - Sex Chromosome (X/SRY)", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8440", testName: "FISH Analysis - DiGeorge/Velocardiofacial Syndrome Panel (22q and 10p)", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8462", testName: "FISH Analysis - Charcot-Marie-Tooth Neuropathy Type 1A", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8467", testName: "FISH Analysis - Hereditary Neuropathy with Liability to Pressure Palsies", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8474", testName: "FISH Analysis - Neurofibromatosis Type 1", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8480", testName: "FISH Analysis - SRY Related Phenotypes", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8486", testName: "FISH Analysis - DiGeorge/Velocardiofacial Syndrome Type I (22q)", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8490", testName: "FISH Analysis - Chromosome X and Y Centromere Analysis", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "8600", testName: "Chromosome Analysis - Blood", medicalApplication: "Pediatrics", testingType: "Other" },
  { testCode: "1390", testName: "Total BluePrint Panel", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1500", testName: "Proband Whole Exome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1600", testName: "Trio Whole Exome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1601", testName: "Sequential Trio Whole Exome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1602", testName: "WES - Additional Affected Sibling", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1603", testName: "Duo Whole Exome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1604", testName: "Quad Whole Exome Sequencing (WES)", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1605", testName: "Adult Screening Exome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1900", testName: "WES Reanalysis", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing" },
  { testCode: "1530", testName: "Proband Whole Exome Sequencing + Chromosomal Microarray Analysis (CMA) (Comprehensive)", medicalApplication: "Pediatrics", testingType: "Whole Exome Sequencing, Chromosomal Microarray Analysis" },
  { testCode: "1800", testName: "Trio Whole Genome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Genome Sequencing" },
  { testCode: "1803", testName: "Duo Whole Genome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Genome Sequencing" },
  { testCode: "1804", testName: "Quad Whole Genome Sequencing (WGS)", medicalApplication: "Pediatrics", testingType: "Whole Genome Sequencing" },
  { testCode: "1810", testName: "Proband Whole Genome Sequencing", medicalApplication: "Pediatrics", testingType: "Whole Genome Sequencing" },
  { testCode: "1897", testName: "WGS Reanalysis", medicalApplication: "Pediatrics", testingType: "Whole Genome Sequencing" },
  { testCode: "1522", testName: "Custom Sequence Analysis - Prenatal", medicalApplication: "Pregnancy", testingType: "-" },
  { testCode: "6105", testName: "Myotonic Dystrophy Type 1 Repeat Expansion Analysis (Prenatal Diagnosis)", medicalApplication: "Pregnancy", testingType: "-" },
  { testCode: "6351", testName: "DMD Deletion/Duplication (Prenatal Diagnosis)", medicalApplication: "Pregnancy", testingType: "-" },
  { testCode: "6574", testName: "FMR1 CGG Repeat Expansion Prenatal Analysis", medicalApplication: "Pregnancy", testingType: "-" },
  { testCode: "BG-24001-P12-5", testName: "Prenatal Noonan Spectrum Disorders/RASopathy Panel", medicalApplication: "Pregnancy", testingType: "-" },
  { testCode: "8410", testName: "FISH Analysis - Prenatal Aneuploidy", medicalApplication: "Pregnancy", testingType: "Chromosome Analysis" },
  { testCode: "8500", testName: "Chromosome Analysis - Prenatal - Amniotic Fluid with AFP", medicalApplication: "Pregnancy", testingType: "Chromosome Analysis" },
  { testCode: "8530", testName: "Chromosome Analysis - Prenatal - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Chromosome Analysis" },
  { testCode: "8540", testName: "Chromosome Analysis - Prenatal - Amniotic Fluid with ACHE", medicalApplication: "Pregnancy", testingType: "Chromosome Analysis" },
  { testCode: "8700", testName: "Chromosome Analysis - Prenatal - CVS", medicalApplication: "Pregnancy", testingType: "Chromosome Analysis" },
  { testCode: "8501", testName: "Alphafetoprotein Analysis - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "8550", testName: "Alpha-fetoprotein and Acetylcholinesterase Analysis - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "8940", testName: "Herpes Simplex Virus 1 & 2 Analysis", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "8945", testName: "Cytomegalovirus (CMV) Analysis", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "8950", testName: "Toxoplasma gondii (TOXO) Analysis", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "8955", testName: "Parvovirus B19 Analysis", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "21200", testName: "PreSeek Non-invasive Prenatal Gene Sequencing Screen", medicalApplication: "Pregnancy", testingType: "Prenatal" },
  { testCode: "1622", testName: "Prenatal Trio Whole Exome Sequencing", medicalApplication: "Pregnancy", testingType: "Prenatal, Whole Exome Sequencing" },
  { testCode: "8656", testName: "Targeted Chromosomal Microarray Analysis - Prenatal - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8657", testName: "Targeted Chromosomal Microarray Analysis - Prenatal - CVS", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8670", testName: "Expanded Chromosomal Microarray Analysis - Prenatal - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8671", testName: "Expanded Chromosomal Microarray Analysis - Prenatal - CVS", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8672", testName: "CMA - Targeted and Limited Karyotype - Prenatal - CVS", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8673", testName: "CMA - Targeted and Limited Karyotype - Prenatal - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8675", testName: "CMA-Expanded and Limited Karyotype - Prenatal - Amniotic Fluid", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8676", testName: "CMA-Expanded and Limited Karyotype - Prenatal - CVS", medicalApplication: "Pregnancy", testingType: "Prenatal, Chromosomal Microarray Analysis" },
  { testCode: "8639", testName: "Chromosomal Microarray Analysis - Tissue", medicalApplication: "Pregnancy", testingType: "Products of Conception" },
  { testCode: "8800", testName: "Chromosome Analysis - Tissue", medicalApplication: "Pregnancy", testingType: "Products of Conception" },
  { testCode: "BG-64000-P158-1", testName: "GeneAware Complete Panel (Female)", medicalApplication: "Pregnancy", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P24-1", testName: "GeneAware ACMG & ACOG Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P39-1", testName: "GeneAware Ashkenazi Jewish Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P421-1", testName: "GeneAware Expanded Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P445-1", testName: "GeneAware Expanded Plus Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P566-1", testName: "GeneAware Comprehensive Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P6-1", testName: "GeneAware Basic Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64000-P611-1", testName: "GeneAware Comprehensive Plus Panel (Female)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P158-1", testName: "GeneAware Complete Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P24-1", testName: "GeneAware ACMG & ACOG Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P39-1", testName: "GeneAware Ashkenazi Jewish Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P421-1", testName: "GeneAware Expanded Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P445-1", testName: "GeneAware Expanded Plus Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P566-1", testName: "GeneAware Comprehensive Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P6-1", testName: "GeneAware Basic Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
  { testCode: "BG-64005-P611-1", testName: "GeneAware Comprehensive Plus Panel (Male)", medicalApplication: "Reproductive Health", testingType: "Carrier Screening" },
];
